### ISSUE TITLE
Failed to run update_iam_data.py

### ISSUE THREAD

**Issue by rezamt** [duo-labs/parliament#107] opened 2020-04-20 01:02 UTC
Hi Team
I am looking at refreshing iam data using [update_iam_data.py](https://github.com/duo-labs/parliament/utils/update_iam_data.py) and I am getting the following error message:

`(env) ➜  utils git:(master) ✗ python update_iam_data.py
Traceback (most recent call last):
  File "update_iam_data.py", line 103, in <module>
    update_html_docs_directory("docs/")
  File "update_iam_data.py", line 34, in update_html_docs_directory
    get_links_from_base_actions_resources_conditions_page()
  File "update_iam_data.py", line 21, in get_links_from_base_actions_resources_conditions_page
    for i in soup.find("div", {"class": "highlights"}).findAll("a"):
AttributeError: 'NoneType' object has no attribute 'findAll'`

**Comment by 0xdabbad00** [comment] 2020-04-20 13:37
Looks like AWS changed the doc format again.  😡  

I just ran an update a week ago, so there shouldn't be much changed, if you just use the last release.

**Comment by 0xdabbad00** [comment] 2020-04-20 14:29
Ranted to AWS here: https://twitter.com/0xdabbad00/status/1252232798905098248

**Comment by jjshoe** [comment] 2020-04-20 14:57
At some point shortly I'll get around to publishing json of my scraping, going public with the site and code shortly: https://beta.iammadeeasy.com

**Comment by 0xdabbad00** [comment] 2020-04-20 15:21
Thanks @jjshoe.  It's unfortunately a moving target as AWS changes their doc format roughly once every month or two on average it seems.  Historically, kmquade with his Policy Sentry project has always figured out how to work around the changes before I've gotten to it, and I've just copy/pasted his code. HIs code is https://github.com/salesforce/policy_sentry/blob/master/policy_sentry/shared/awsdocs.py
mine is https://github.com/duo-labs/parliament/blob/master/utils/update_iam_data.py

**Comment by kmcquade** [comment] 2020-04-21 01:06
I should also mention that the HTML docs are also stored as backup here:
https://github.com/salesforce/policy_sentry/tree/master/policy_sentry/shared/data/docs for reproducibility, even when the AWS docs change. 

My own IAM definition (current structure borrowed from Parliament, plus an access overrides mechanism) is in the parent folder.

**Comment by kmcquade** [comment] 2020-04-21 01:28
I figured it out. We have to remove "partial.html" from the base documentation URL. https://github.com/duo-labs/parliament/blob/master/utils/update_iam_data.py#L13

PR coming shortly.

**Comment by 0xdabbad00** [comment] 2020-04-28 18:06
This was resolved in the recent release.

**Closed by 0xdabbad00** 2020-04-28 18:06 UTC
Labels: bug
